blogproject/urls.py
from django.contrib import admin
from django.urls import path, include
from web.feeds import AllPostsRssFeed
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web.urls')),
    path('', include('comments.urls')),
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    path('all/rss/', AllPostsRssFeed(), name='rss'),
]

web/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView
from .import views

app_name = 'web'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('posts/<int:pk>/', views.PostDetailView.as_view(), name='detail'),
    path('archives/<int:year>/<int:month>/', views.ArchiveView.as_view(), name='archive'),
    path('categories/<int:pk>/', views.CategoryView.as_view(), name='category'),
    path('tags/<int:pk>/', views.TagView.as_view(), name='tag'),
    path('search/',views.search, name='search'),
    path('about/',views.about,name='about'),
    path('contact/',views.contact,name='contact'),
    path('fullwidth/', views.fullwidthView.as_view(), name='fullwidth'),

]
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/web/inclusions/_tags.html
<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
<div class="widgeta">
  <div class="widget widget-category1">
    <div style="width: 100%;float: left;box-shadow: 0 0 15px #000000;">
      <div style="width: 100%;float: left;box-shadow: 0 0 10px #ffffff inset;">
         <h3 class="widget-title">标签云</h3>
         <div style="height: 3px;width: 5%;float: left;"></div>
         <div style="height: 3px;width: 25%;float: left;background-color: #d7e9f5;"></div>
         <div style="height: 3px;width: 65%;float: left;background-color: #333;"></div>
         <div style="height: 3px;width: 5%;float: left;"></div>
        </div>
       </div>
      <div class="widgetb widgetb2">
  <ul>
    {% for tag in tag_list %}
      <li style="background-color:{{ tag.tagColor }};">
        <h5 class="glyphicon glyphicon-send"></h5><div>
          <a href="{% url 'web:tag' tag.pk %}" style="color:{{ tag.tagColor }} ;">{{ tag.name }}</a>
        </div>
      </li>
    {% empty %}
      暂无标签！
    {% endfor %}
  </ul>
</div>
</div>
</div>
</body>
</html>

templates/web/inclusions/archives.html
{% block toc %}
{% if post.toc %}
<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
<div class="widgeta">
  <div class="widget widget-archives">
    <div style="width: 100%;float: left;box-shadow: 0 0 15px #000000;">
      <div style="width: 100%;float: left;box-shadow: 0 0 10px #ffffff inset;">
        <h3 class="widget-title">归档</h3>
        <div style="height: 3px;width: 5%;float: left;"></div>
        <div style="height: 3px;width: 25%;float: left;background-color: #d7e9f5;"></div>
        <div style="height: 3px;width: 65%;float: left;background-color: #333;"></div>
        <div style="height: 3px;width: 5%;float: left;"></div>
      </div>
    </div>
<div class="widgetb widgetb2">
  <ul>
    {% for date in date_list %}
      <li>
        {{ post.toc|safe }}
      </li>
    {% empty %}
      暂无归档！
    {% endfor %}
  </ul>

</div>
</div>
</div>
{% endif %}
{% endblock toc %}
</body>
</html>

templates/web/inclusions/categories.html
<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
<div class="widgeta">
  <div class="widget widget-category">
    <div style="width: 100%;float: left;box-shadow: 0 0 15px #000000;">
      <div style="width: 100%;float: left;box-shadow: 0 0 10px #ffffff inset;">
        <h3 class="widget-title">分类</h3>
        <div style="height: 3px;width: 5%;float: left;"></div>
        <div style="height: 3px;width: 25%;float: left;background-color: #d7e9f5;"></div>
        <div style="height: 3px;width: 65%;float: left;background-color: #333;"></div>
        <div style="height: 3px;width: 5%;float: left;"></div>
      </div>
    </div>
  <div class="widgetb widgetb3">
  <ul>
    {% for category in category_list %}
      <li>
         <div>{{ category.num_posts }}</div><h5 class="glyphicon glyphicon-pushpin"></h5><a href="{% url 'web:category' category.pk %}">{{ category.name }}</a>
       </li>
    {% empty %}
      暂无分类！
    {% endfor %}
  </ul>
</div>
</div>
</div>
</body>
</html>

templates/web/inclusions/recent_posts.html
<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
<div class="widgeta">
  <div class="widget widget-recent-posts">
    <div style="width: 100%;float: left;box-shadow: 0 0 15px #000000;">
      <div style="width: 100%;float: left;box-shadow: 0 0 10px #ffffff inset;">
        <h3 class="widget-title">最新文章</h3>
        <div style="height: 3px;width: 5%;float: left;"></div>
        <div style="height: 3px;width: 25%;float: left;background-color: #d7e9f5;"></div>
        <div style="height: 3px;width: 65%;float: left;background-color: #333;"></div>
        <div style="height: 3px;width: 5%;float: left;"></div>
      </div>
  </div>
  <div class="widgetb widgetb1">
    <ul>
      {% for post,one,num in array %}
      
        <li>
          <div style="background-color: {{ one }}">{{ num }}</div><a href="{{ post.get_absolute_url }}">{{ post.title}}</a>
        </li>
      {% empty %}
        暂无文章！
      {% endfor %}
    </ul>
  </div>
</div>
</div>
</body>
</html>

templates/web/inclusions/tags.html
<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
<div class="widget widget-tag-cloud">
  <h3 class="widget-title">标签云</h3>
  <ul>
    {% for tag in tag_list %}
      <li>
        <a href="{% url 'web:tag' tag.pk %}">{{ tag.name }} <span class="post-count">({{ tag.num_posts }})</a>
      </li>
    {% empty %}
      暂无标签！
    {% endfor %}
  </ul>
</div>
</body>
</html>