blogproject/urls.py
from django.contrib import admin
from django.urls import path, include
from web.feeds import AllPostsRssFeed
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web.urls')),
    path('', include('comments.urls')),
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    path('all/rss/', AllPostsRssFeed(), name='rss'),
]

userprofile/urls.py
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [
    # 用户登录
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
]

web/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView
from .import views

app_name = 'web'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('posts/<int:pk>/', views.PostDetailView.as_view(), name='detail'),
    path('archives/<int:year>/<int:month>/', views.ArchiveView.as_view(), name='archive'),
    path('categories/<int:pk>/', views.CategoryView.as_view(), name='category'),
    path('tags/<int:pk>/', views.TagView.as_view(), name='tag'),
    path('search/',views.search, name='search'),
    path('about/',views.about,name='about'),
    path('contact/',views.contact,name='contact'),
    path('fullwidth/', views.fullwidthView.as_view(), name='fullwidth'),

]
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
    {% load static %}
    {% load web_extras %}
<html>
<head>
    <title>我太富博客</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
   <!-- <link rel="icon" href="{% static 'web/img/favicon.ico' %}" type="image/x-icon" /> -->
      <link rel="shortcut icon" href="{% static 'web/img/favicon.ico' %}" />
   

    <!-- css -->
    <style>
     .codehilite {
      padding: 0;
    }

    /* for block of numbers */
    .hljs-ln-numbers {
      -webkit-touch-callout: none;
      -webkit-user-select: none;
      -khtml-user-select: none;
      -moz-user-select: none;
      -ms-user-select: none;
      user-select: none;

      text-align: center;
      color: #ccc;
      border-right: 1px solid #CCC;
      vertical-align: top;
      padding-right: 5px;
    }

    .hljs-ln-n {
      width: 30px;
    }

    /* for block of code */
    .hljs-ln .hljs-ln-code {
      padding-left: 10px;
      white-space: pre;
    }
    </style>


    <link href="https://cdn.bootcss.com/highlight.js/9.18.1/styles/atom-one-dark.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static 'web/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'web/css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'web/css/custom.css' %}">

    <!-- js -->
     <script src="{% static 'web/js/jquery-2.1.3.min.js' %}"></script>
     <script src="{% static 'web/js/bootstrap.min.js' %}"></script>
     <script src="{% static 'web/js/pace.min.js' %}"></script>
     <script src="{% static 'web/js/modernizr.custom.js' %}"></script>
</head>
<body id="single">
<div class="kaitou">
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <img src="{% static 'web/img/logo.png' %}" style="height: 50px;">
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                                <ul class="nav navbar-nav navbar-right">
                                    <li class="cl-effect-8"><h4 class="glyphicon glyphicon-home"><a href="{% url 'web:index' %}" data-hover="首页"> 首页</a></h4></li>
                                    <li class="cl-effect-8"><h4 class="glyphicon glyphicon-book"><a href="{% url 'web:fullwidth' %}" data-hover="博客"> 博客</a></h4></li>
                                    <li class="cl-effect-8"><h4 class="glyphicon glyphicon-user"><a href="{% url 'web:about' %}" data-hover="关于"> 关于</a></h4></li>
                                    <li class="cl-effect-8"><h4 class="glyphicon glyphicon-phone"><a href="{% url 'web:contact' %}" data-hover="联系"> 联系</a></h4></li>
                            {% if user.is_authenticated %}
                            <!-- 如果用户已经登录，则显示用户名下拉框 -->
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                  {{ user.username }}
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                  <a class="dropdown-item" href='{% url "userprofile:logout" %}'>退出登录</a>
                                </div>
                            </li>
                        <!-- 如果用户未登录，则显示 “登录” -->
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'userprofile:login' %}">登录</a>
                            </li>
                        <!-- if 语句在这里结束 -->
                        {% endif %}
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="{% url 'web:search' %}">
                          <input type="search" name="q" placeholder="搜索" required>
                          <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
      </div>
    </header>
{% if messages %}
    {% for message in messages %}
      <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                aria-hidden="true">&times;</span></button>
        {{ message }}
      </div>
    {% endfor %}
{% endif %}
</div>
<div class="copyrights">Collect from <a href="http://www.cssmoban.com/">网页模板</a></div>


<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">
                {% block main %}
                {% endblock main %}
            </main>
            <aside class="col-md-4">
                  {% block toc %}
                  {% endblock toc %}
                  {% show_recent_posts %}
                  {% show_categories %}
                  {% show_archives %}
                  {% show_tags %}
                <div class="rss">
                    <a href="{% url 'rss' %}"><span class="ion-social-rss-outline"></span> RSS 订阅</a>
                </div>
            </aside>
        </div>
    </div>
</div>
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="footera col-md-12 ">
                <a href="{% url 'web:contact' %}" class="no_look">联系我们</a>|<a href="{% url 'web:index' %}">关于博客</a>|<a href="#">关于广告</a>|<a href="#" class="no_look">关于微博</a>
            </div>
            <div class="footerb col-md-12 ">
                @2020 wtf.zhangxinyu.org/ 我太富队伍 创作
            </div>
        </div>
    </div>
</footer>

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="{% url 'web:index' %}">首页</a></li>
            <li><a href="full-width.html">博客</a></li>
            <li><a href="about.html">关于</a></li>
            <li><a href="contact.html">联系</a></li>
        </ul>
    </nav>
</div>


<script src="{% static 'web/js/script.js' %}"></script>
<script src="https://cdn.bootcss.com/highlight.js/9.18.1/highlight.min.js"></script>
<script src="https://cdn.bootcss.com/highlightjs-line-numbers.js/2.7.0/highlightjs-line-numbers.min.js"></script>
<body>
  <script src="https://cdn.bootcss.com/highlight.js/9.15.8/highlight.min.js"></script>
  <script src="https://cdn.bootcss.com/highlightjs-line-numbers.js/2.7.0/highlightjs-line-numbers.min.js"></script>
  <script>
    hljs.initHighlightingOnLoad();
    hljs.initLineNumbersOnLoad();
  </script>
</body>
</html>